stages:
  - check
  - build

default:
  image: golang:1.24
  interruptible: true

variables:
  GOPROXY: "https://goproxy.cn"
  GOSUMDB: "off"
  GOCACHE: "/tmp/go-build"

before_script:
  - go version

format-check:
  stage: check
  script:
    - gofmt -l api cmd internal
    - test -z "$(gofmt -l api cmd internal)"

build-manager:
  stage: build
  script:
    - go build -o bin/manager ./cmd/main.go
  artifacts:
    paths:
      - bin/manager
    expire_in: 7 days
