stages:
  - check
  - build

default:
  image: golang:1.24
  interruptible: true

variables:
  GOPROXY: "off"
  GOSUMDB: "off"
  GOMODCACHE: "$CI_PROJECT_DIR/.cache/go/pkg/mod"
  GOCACHE: "$CI_PROJECT_DIR/.cache/go-build"

cache:
  key:
    files:
      - go.sum
  paths:
    - .cache/go/pkg/mod/
    - .cache/go-build/

before_script:
  - go version

format-check:
  stage: check
  script:
    - gofmt -l api cmd internal
    - test -z "$(gofmt -l api cmd internal)"

build-manager:
  stage: build
  script:
    - go build -o bin/manager ./cmd/main.go
  artifacts:
    paths:
      - bin/manager
    expire_in: 7 days
