apiVersion: aiinfra.example.com/v1alpha1
kind: VLLMService
metadata:
  labels:
    app.kubernetes.io/name: vllmservice-operator
    app.kubernetes.io/managed-by: kustomize
  name: vllmservice-sample
spec:
  # TODO(user): Add fields here
